---
# Application secrets (SECRET_KEY, KREA_API_KEY)
# In production inject via external-secrets / vault
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kreaimggen.fullname" . }}-app-secret
  labels:
    {{- include "kreaimggen.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.backend.secretEnv.SECRET_KEY | b64enc | quote }}
  krea-api-key: {{ .Values.backend.secretEnv.KREA_API_KEY | b64enc | quote }}
---
# Broker credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kreaimggen.fullname" . }}-broker-secret
  labels:
    {{- include "kreaimggen.labels" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
---
# Service Account
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kreaimggen.serviceAccountName" . }}
  labels:
    {{- include "kreaimggen.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
